name: master_thesis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - tensorflow
  - keras
  - pytorch
  - transformers
  - nltk
  - gensim
  - statsmodels
  - pandas-datareader
  - fredapi
  # - finbert
  - pip:
    - nltk
    - transformers
    - matplotlib
    - seaborn
    - graphviz
    - pydot
    - yfinance
